version: '3'
services:
    nginx_instance:
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/usr/share/nginx/html
            - ./nginx/default:/etc/nginx/conf.d/default.conf
            - ./logs/nginx_access.log:/var/log/nginx/default_access.log
            - ./logs/nginx_error.log:/var/log/nginx/default_error.log
              #restart: always
        depends_on:
            - fpm_instance
            - wordpress_instance

    fpm_instance:
        #image: php:fpm
        #fpm这种可能会有扩展的东西还是自己写dockerfile比较好
        build: .
        expose:
            - "9000"
        volumes:
            - ./www:/usr/share/nginx/html
        depends_on:
            - mysql_instance
              #- redis_instance

    mysql_instance:
        image: mysql:8.0
        environment: 
            #root密码
            MYSQL_ROOT_PASSWORD: "123456"
            # 创建一个db和user
            MYSQL_DATABASE: 'wordpress'
            MYSQL_USER: 'wp'
            MYSQL_PASSWORD: '123456'
            #restart: always

    redis_instance:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            #restart: always

    wordpress_instance:
        depends_on:
            - mysql_instance
            - redis_instance
        image: wordpress
              #restart: always
        environment:
            WORDPRESS_DB_HOST: mysql_instance:3306
            WORDPRESS_DB_USER: 'wp'
            WORDPRESS_DB_PASSWORD: '123456'


